php_schulung_de_form_demo:
    resource: "@PhpSchulungDeFormDemoBundle/Controller/"
    type:     annotation
    prefix:   /

php_schulung_de_session_demo:
    resource: "@PhpSchulungDeSessionDemoBundle/Controller/"
    type:     annotation
    prefix:   /

